### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by keqingrong** [keqingrong/notes#3]

**Comment by keqingrong** [comment]
# JavaScript设计模式
### 书
- [ ] [Learning JavaScript Design Patterns](https://addyosmani.com/resources/essentialjsdesignpatterns/book/)

### 文章
- [ ] [JavaScript Design Patterns](https://carldanley.com/javascript-design-patterns/)

**Comment by keqingrong** [comment]
Backbone 资料
- [Developing Backbone.js Applications](https://addyosmani.com/backbone-fundamentals/)
- [源码](http://backbonejs.org/docs/backbone.html)

**Comment by keqingrong** [comment]
- [ ] [Other Module Notes](https://requirejs.org/docs/api.html#modulenotes)
- [ ] [Simple one page app](https://github.com/volojs/create-template)
- [ ] [Multipage app](https://github.com/requirejs/example-multipage)
- [ ] [Multipage app with shim config](https://github.com/requirejs/example-multipage-shim)

**Comment by keqingrong** [comment]
# SASS
- [ ] [Control Directives & Expressions](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#control_directives__expressions)

**Comment by keqingrong** [comment]
- [ ] [WebComponents](https://www.w3.org/wiki/WebComponents/)

**Comment by keqingrong** [comment]
- [ ] 《Single Page Web Applications》|《单页Web应用：JavaScript从前端到后端》
- [ ] 《Secrets of the JavaScript Ninja》|《JavaScript 忍者秘籍》

**Comment by keqingrong** [comment]
# 算法
- 排序算法
- 搜索算法
- 动态规划

# 数据结构
- 二叉树
 - ALV树
 - 红黑树
- 二叉堆

**Comment by keqingrong** [comment]
# 移动设备
## 1. 系统
- Android
- iOS
## 2. 分辨率
## 3. 浏览器
- Android
 - UC 浏览器
 - QQ 浏览器
 - Chrome
 - Opera
- iOS
 - Safari
 - Chrome
